# Generated by Django 3.2.6 on 2021-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='Treacher',
        ),
        migrations.AddField(
            model_name='academic',
            name='Teacher',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='Student',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='studentsemester',
            field=models.CharField(choices=[('', 'Semester'), ('Not Applicable', 'Not Applicable'), ('FirstSemester', 'First Semester'), ('SecondSemester', 'Second Semester '), ('ThirdSemester', 'Third Semester'), ('FourthSemester', 'Fourth Semester'), ('FifthSemester', 'Fifth Semester'), ('SixthSemester', 'Sixth Semester'), ('SeventhSemester', 'Seventh Semester'), ('EighthSemester', 'Eighth Semester')], default='First Semester', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('', 'Semester'), ('Not Applicable', 'Not Applicable'), ('FirstSemester', 'First Semester'), ('SecondSemester', 'Second Semester '), ('ThirdSemester', 'Third Semester'), ('FourthSemester', 'Fourth Semester'), ('FifthSemester', 'Fifth Semester'), ('SixthSemester', 'Sixth Semester'), ('SeventhSemester', 'Seventh Semester'), ('EighthSemester', 'Eighth Semester')], default='First Semester', max_length=40),
        ),
    ]
